# Generated by Django 3.0.2 on 2020-11-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20201117_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversation.Conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='discount_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
